### ISSUE TITLE
Allow setting of path_patterns via service

### ISSUE THREAD

**Issue by wizhippo** [liip/LiipThemeBundle#108]
Currently we have a multisite setup and change the theme in an kernel event handler.  In this handle I would like to be able to update path_patterns so i can set them fallbacks differently based on the site.

Should I make the liip_theme.file_locator service public and add a public method to allow path_patterns to be changed?

Is this useful to others?  Should I create a PR for the change?

**Comment by lsmith77** [comment]
ping

**Comment by wizhippo** [comment]
We just settled on just one fall back for all sites instead of allowing each site to have a different fall back.  Though this feature would be nice we do not need it any more.
