### ISSUE TITLE
'Unable to find template' errors since update of assetic

### ISSUE THREAD

**Issue by Sander-Toonen** [liip/LiipThemeBundle#109]
After updating the symfony/assetic-bundle from version v2.3.1 to version v2.4.0 I start to see errors thrown by the liip theme TemplateLocator on every request.

This is due to the following commit in assetic-bundle, which makes that errors are no longer suppressed.
https://github.com/symfony/AsseticBundle/commit/ff46000dd73411bbe812238f38bcacaf3f94b504 

I have my theme template overrides in ``src/IB/MyBundle/Resources/themes/views/{theme}/`` so that the override for the `default`-theme for ``src/IB/MyBundle/Resources/views/Header/main.html.twig`` resides in ``src/IB/MyBundle/Resources/themes/default/views/IBMyBundle/Header/main.html.twig``

The error list contains errors like the one below for every template in the themes directory:
> The template "IBMyBundle:views/IBMyBundle/Header:main.html.twig" contains an error: Unable to find template "IBMyBundle:views/IBMyBundle/Header:main.html.twig".

However, all templates are shown as they should be and apart from the error messages, nothing seems wrong. Does anyone have an idea how to get rid of these messages?

**Comment by dbu** [comment]
is this fixed by https://github.com/liip/LiipThemeBundle#assetic-integration - or otherwise related to https://github.com/liip/LiipThemeBundle/pull/106?

**Comment by Sander-Toonen** [comment]
@dbu The error indeed disappeared. However I encounter some other regression. Some assets are compiled multiple times (dumping time has skyrocketed) and using assetic:dump with the Spork library gives errors. Would you like me to open issues with more detail for these issues? (One for each problem or a single one?)

**Comment by lsmith77** [comment]
cc @dantleech

**Comment by dbu** [comment]
@dantleech added things to make assetic dump all themes. not sure if there could be a way to de-duplicate assetic into not dumping the same thing multiple times. but yeah, best open an issue about the duplication (maybe its more of an assetic issue than something we can do here, not sure) and one about the spork problem.

i can't promise to work on this, i was just trying to clean up issues here a bit. but maybe somebody else can.

**Comment by Sander-Toonen** [comment]
For me, this issue is fixed with #109 and #122.

@fotomerchant Can you confirm this?
