### ISSUE TITLE
[RFC] Drop Symfony < 2.3 support

### ISSUE THREAD

**Issue by stloyd** [liip/LiipThemeBundle#119]
As support for versions < 2.3 (and for 2.4) already ended, there is no reason too support them actively in this bundle.

**Comment by lsmith77** [comment]
yeah .. I agree. can you submit a PR to update the composer.json and maybe quickly go through the code to look for BC hacks.

**Comment by lsmith77** [comment]
ping

**Comment by lsmith77** [comment]
done with https://github.com/liip/LiipThemeBundle/pull/131
