### ISSUE TITLE
Changing active theme on the fly in console command

### ISSUE THREAD

**Issue by Sander-Toonen** [liip/LiipThemeBundle#120]
I have a console command that sends HTML email messages to users. The layout depends on a theme. Users can have a theme set in their profile. Is there a way to change to active theme on the fly so Twig renders every mail with the appropriate theme?

**Comment by lsmith77** [comment]
it should be possible via the ``liip_theme.active_theme`` service

**Comment by Sander-Toonen** [comment]
@lsmith77 Unfortunately, that is not correct. The following fails:

I have a mail template _message.html.twig_ which includes a template _header.html.twig_, both templates are overridden for a theme _Unicorn_ and a theme _Rainbow_. I have a user  _Bob_ which uses theme _Unicorn_ and a user _Alice_ using theme _Rainbow_. Now I want to send them a daily mail using a cron command:

- Send a mail to user _Bob_ with theme  _Unicorn_:
    - Set theme to _Unicorn_
    - Render template _message.html.twig_ (which includes template _header.html.twig_)
    - Send mail
- Send a mail to user _Alice_ with theme _Rainbow_:
    - Set theme to _Rainbow_
    - Render template _message.html.twig_ (which includes template _header.html.twig_)
    - Send mail

Bob will receive the entire mail in the _Unicorn_ theme, as expected.
However Alice will only see the content of _message.html.twig_ in the _Rainbow_ theme. The included _header.html.twig_  will be using the _Unicorn_ theme even though Alice should be seeing it in the _Rainbow_ theme.

It seems that in some way a cache is set on the first use of an included template and that every other use of that template in the same lifecycle of a command will be using that template even though another theme has been set.

**Comment by Sander-Toonen** [comment]
Follow up:

I found the source of the problem.

The Symfony\Bundle\TwigBundle\Loader\FilesystemLoader is caching files for templates in findTemplate() line 93. That means that during the lifecycle of the FilesystemLoader, template files will be cached by name.

Any ideas on how to approach this issue?

**Comment by wizhippo** [comment]
I believe a modified FilesystemLoader would be the correct route.  I have not tested this thoroughly but here is what I have tried. https://gist.github.com/wizhippo/7623decc16811bbb2a18.  You can see on line 52 the active theme is taken into account.

**Comment by lsmith77** [comment]
can you submit a PR for this idea?

**Comment by nocive** [comment]
I know this is a very old issue but thought I'd post my solution here for others that might come across this.
We were facing this problem and ended up having to override the `FilesystemLoader` class because of the `findTemplate` method:

```php
protected function findTemplate($template, $throw = true)
{
    $logicalName = $cacheName = (string) $template;

    // this is the crucial bit since the active theme name was not being considered
    // for the $logicalName and $cacheName variables
    if ($this->activeTheme) {
        $cacheName .= '|' . $this->activeTheme->getName();
    }

    // rest of the method as is ...
}
