### ISSUE TITLE
Assets are dumped multiple times when using assetic_integration

### ISSUE THREAD

**Issue by Sander-Toonen** [liip/LiipThemeBundle#121]
Follow up on #109

When dumping assets with ```assetic_integration: true``` some assets are compiled and dumped multiple times using the same name. This also results in assetic not being able to resolve the route to these assets. A pull request will follow soon that will keep the TwigFormulaLoader from returning equivalent asset formulae.

**Comment by Sander-Toonen** [comment]
Pull request: #122

**Comment by dbu** [comment]
#122 was merged. thanks again!
