### ISSUE TITLE
switch controller based on theme

### ISSUE THREAD

**Issue by dbu** [liip/LiipThemeBundle#133]
in our project, we needed to switch controllers based on the theme. we came up with the following. would it make sense to add this to the bundle? any inputs on it? 

```yaml
some_route:
    path: /stuff
    defaults:
        _controller: controller.stuff:pageAction
        theme_controllers:
            themename:  controller.themeStuff:pageAction
```

```php
<?php

namespace AppBundle\Listener;

use Symfony\Component\HttpKernel\Event\GetResponseEvent;

/**
 * Listener to rewrite controllers to new application depending on the theme.
 */
class ThemeRoutingListener
{
    /**
     * @var string Name of the cookie that tells the current theme.
     */
    private $themeCookie;

    const ATTRIBUTE_KEY = 'theme_controllers';

    /**
     * @param string $themeCookie Name of the cookie that tells the current theme
     */
    public function __construct($themeCookie)
    {
        $this->themeCookie = $themeCookie;
    }

    /**
     * Kick in right after routing and check if the route defines options to
     * use a different controller for the new theme.
     *
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();
        if (!$request->cookies->has($this->themeCookie)
            || !$request->attributes->has(static::ATTRIBUTE_KEY)
        ) {
            return;
        }

        $theme = $request->cookies->get($this->themeCookie);
        if (isset($request->attributes->get(static::ATTRIBUTE_KEY)[$theme])) {
            $request->attributes->set('_controller', $request->attributes->get(static::ATTRIBUTE_KEY)[$theme]);
        }
    }
}
```

```xml
        <service id="listener.theme_routing" class="AppBundle\Listener\ThemeRoutingListener">
            <argument>%theme_switcher_cookiename%</argument>
            <tag name="kernel.event_listener" event="kernel.request" method="onKernelRequest" priority="31" />
            <!-- routing is priority 32 so we come right after the routing -->
        </service>
```

/cc @thormeier

**Comment by lsmith77** [comment]
I think generally the idea was that such differences in logic would be "driven" by the template by conditional logic there. Then again, this is of course also not so ideal for testing. However this approach also seems a bit fragile .. I mean if everybody starts making the controllers dynamic based on some listener things would be hard to combine.

**Comment by lsmith77** [comment]
ah .. now I get your plan .. A/B testing! now things are getting more interesting. But I am not sure if such a thing should be driven by the theme ..

**Comment by dbu** [comment]
indeed, our use case is A/B testing. we use the theme mechanism for this
anyways, so allowing to change the controller seemed like a good idea.

regarding fragility: we do use the JMSi18nRoutingBundle which interacts
quite unfriendly with other routers - but as this thing comes *after*
the routing and does not care about URLs, only about the controller, it
should not be that fragile i think. but maybe its too much of an edge
case for this bundle. if you think so, i can also explain this in a blog
post - its rather simple to implement in a project directly.

**Comment by dbu** [comment]
so: blog post or pull request?

**Comment by lsmith77** [comment]
lets see what the community thinks https://twitter.com/lsmith/status/610362955411140608

**Comment by lsmith77** [comment]
ok .. lets do a PR

**Comment by dbu** [comment]
can do that in july. but add some warning about A/A testing with the doc...
