### ISSUE TITLE
Use options instead of default for theme controllers

### ISSUE THREAD

**Issue by dbu** [liip/LiipThemeBundle#135]
When we added controller per theme in #134 we decided to let the user configure the alternate controllers in the route `defaults`. this means we need this cleanup code here: https://github.com/liip/LiipThemeBundle/blob/master/EventListener/ThemeControllerListener.php#L47-L53

Could we instead move that to the `options` part of the routing to avoid messing up the defaults? As there was no release of the 1.4 dev yet, we could fix this without keeping BC code in place.

@thormeier do you see any problem using options here?

**Comment by lsmith77** [comment]
fine for me

**Comment by thormeier** [comment]
Fine for me as well, go ahead.

**Comment by dbu** [comment]
hm. the drawback with that is that we would need to go to the router, fetch the route collection and pick the "current" route to access the options. as done in https://github.com/thormeier/breadcrumb-bundle/blob/master/Provider/BreadcrumbProvider.php#L78

probably a bit too heavy on performance to do that in every request. lets keep with the way we have now.
