### ISSUE TITLE
No work to Symfony 2.7

### ISSUE THREAD

**Issue by zhouitpro** [liip/LiipThemeBundle#139]
i am use symfony new myproject and download the Bundle

config.xml
liip_theme:
    themes: ['theme1', 'theme2', 'theme3']
    active_theme: 'theme2'
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%current_device%%/%%template%%
            - %%app_path%%/themes/fallback_theme/%%current_device%%/%%template%%
            - %%app_path%%/views/%%current_device%%/%%template%%

routing.xml
liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

Appkernel.php add line:
  new Liip\ThemeBundle\LiipThemeBundle(),

no work.
# 

when disable the code after work

![image](https://cloud.githubusercontent.com/assets/342575/11470330/b490b260-9797-11e5-97cf-a8efddd052e9.png)

![image](https://cloud.githubusercontent.com/assets/342575/11470358/dba7eb0c-9797-11e5-8a92-4ed79a1b6873.png)

![image](https://cloud.githubusercontent.com/assets/342575/11470359/dbd3c948-9797-11e5-886d-11e91c6d5500.png)

**Comment by lsmith77** [comment]
I seem to remember that we had similar issues in the past already ..

/cc @dbu

**Comment by dbu** [comment]
sorry lukas, i don't remember having this problem.
are you running in app_dev.php or with the prod environment? if in prod, did you clear the prod cache with `app/console cache:clear --env=prod`? or are you switching themes inside the same request?
