### ISSUE TITLE
Active theme cached across requests

### ISSUE THREAD

**Issue by umpirsky** [liip/LiipThemeBundle#145]
I am setting active theme based on subdomain:

``` php
class ThemeRequestListener
{
    private $activeTheme;

    public function __construct(ActiveTheme $activeTheme)
    {
        $this->activeTheme = $activeTheme;
    }

    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            return;
        }

        if (0 !== strpos($event->getRequest()->server->get('HTTP_HOST'), 'umpirsky.')) {
            return;
        }

        $this->activeTheme->setName('umpirsky');
    }
}

```

My config is:

```
liip_theme:
    themes: ['umpirsky']
    assetic_integration: true

```

It works fine, except active theme is somehow "cached" across requests, and appears on root domain as well.

Where is this stored?

Can I disable this and always choose theme based on current request?

**Comment by andrerom** [comment]
Would be great to vary this on a context, have similar thing in eZ Platform where we identify a context *(SiteAccess)* based on request and will need to vary theme cache on this.

**Comment by Sander-Toonen** [comment]
I see a lot of people that check whether the request is the Master request in the event listener, but doesn't that prevent you from theming error pages?

**Comment by umpirsky** [comment]
@Sander-Toonen Maybe...didn't test. But still, out of scope of this issue, isn't it?

**Comment by Sander-Toonen** [comment]
Yes sorry, out of scope indeed. I was just wondering.

Regarding your issue, do you have just one theme? Could you try this config?

    liip_theme:
        themes: ['default', 'umpirsky']
        active_theme: 'default'
        assetic_integration: true

And just to be sure, you don't have any cookies that instruct the theme to be loaded of some weird Varnish setup?

**Comment by umpirsky** [comment]
I tried that config, same issue. Nothing in cookies. Thanks.

**Comment by oleg-andreyev** [comment]
> except active theme is somehow "cached" across requests
@umpirsky could please explain? So when you are calling `ActiveTheme::getName` before `ThemeRequestListener`, it returns `umpirsky`?

**Comment by umpirsky** [comment]
Sorry, this issue is almost 2 years old. I don't remember all the details. Closing, thanks.
