### ISSUE TITLE
Can I force always load first an own bundle ? 

### ISSUE THREAD

**Issue by Chrysweel** [liip/LiipThemeBundle#152]
Hello.

I want force that LiipThemeBundle always load first in my own bundle: CustomBundle

i.e I want to have a CustomBundle and here I overwrite any template of all project.

I see that I have the parameters path_patterns, I think that it is the key.

But I can not properly write the route, because the template is not overwrite.

My CustomBundle is in src/CustomBundle..

Somebody can help me please ?

I know do it with my own code with overwrite class twig.loader.filesystem in compilerPass, but I discover this bundle and I want use this code, that I think that is more correct way.

**Comment by lsmith77** [comment]
what about just using https://symfony.com/doc/current/reference/configuration/twig.html#paths ?
