### ISSUE TITLE
Fatal error in FileSystemLoader

### ISSUE THREAD

**Issue by fotomerchant** [liip/LiipThemeBundle#157]
A recent commit to https://github.com/symfony/symfony/commit/2d4268936a05254a4e8b2d1ed7d2fc08881a098b causes the following error with the LiipThemeBundle:

`Catchable Fatal Error: Argument 3 passed to Liip\ThemeBundle\Twig\Loader\FilesystemLoader::__construct() must be an instance of Liip\ThemeBundle\ActiveTheme, string given`

The pull request is here: https://github.com/symfony/symfony/pull/20727

I've verified that reverting the above commit rectifies the issue. I will try to find time to figure out exactly what has happened and see whether there is a BC fix

**Comment by j0k3r** [comment]
Upgrading to Symfony 3.2.1 and project is broken because of that.

**Comment by danjaredg** [comment]
Upgrading to Symfony 3.2.1 is broken

**Comment by lsmith77** [comment]
fixed via #159
