### ISSUE TITLE
Unable to find template "register_content.html.twig|myTheme" in @FOSUser/Registration/register.html.twig at line 4.

### ISSUE THREAD

**Issue by nicosomb** [liip/LiipThemeBundle#160]
Hello, 

We use LiipThemeBundle (1.4.3) and FOSUserBundle (2.0.x-dev, [694e6d3](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/694e6d36588f128e8ee0abe622bdcb4c102bd75e)).
Since [this commit in FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/dd1fa8fbb6df2d6037c136cc2b29a568f250069e), I have this error: 

```
Unable to find template "register_content.html.twig|myTheme" in @FOSUser/Registration/register.html.twig at line 4.
```

Before this commit, in the `locate()` method of `Liip\ThemeBundle\Locator\FileLocator`, I have `@FOSUserBundle/Resources/views/Registration/register.html.twig` in `$name`.
After this commit, I have `"views/register_content.html.twig"`.

That's why I don't have the good behavior in my application.

**Comment by oleg-andreyev** [comment]
Please correct link to FOSUserBundle

**Comment by nicosomb** [comment]
Done

**Comment by nicosomb** [comment]
I think it's related to https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2376. I close here.
