### ISSUE TITLE
Set themes and active themes from PHP code

### ISSUE THREAD

**Issue by emulienfou** [liip/LiipThemeBundle#169]
Hi, after following the steps of the posts in the #148 issue and creating an event listener, I'm trying to set an array of themes from a directory using `DirectoryIterator` class and the active theme from the `parameters.yml` file but having some troubles.

After some tests, I end up with this message: `The active theme "" must be in the themes list () in .` only if I'm not declaring the next configuration in my `config.yml` file:

```yaml
liip_theme:
    themes: ['default']
    active_theme: default
```
So for using the event listener, I need to set at least one *themes* and one *active_theme* in my configuration file and after that I'm able to override it!

Is there an other way to achieve that without predefined values for `themes` and `active_theme`?

Thanks

**Comment by clytemnestra** [comment]
As much as I remember you need to set a default theme no matter what. But you can immediately override it, anyways.

**Comment by 7thcubic** [comment]
```php

public function prepend(ContainerBuilder $container)
    {
        $bundles = $container->getParameter('kernel.bundles');

        if (isset($bundles['LiipThemeBundle'])) {
            $themes = [];
            $finder = new Finder();
            foreach($finder->path('/\/Resources\/themes\/.*$/')->directories()->in($container->getParameter('kernel.root_dir').'/..') as $directory)
            {
                if(strstr($directory->getPath(), "Tests") === false)
                {
                    if(!in_array($directory->getFilename(), $themes))
                        $themes[] = $directory->getFilename();
                }
            }
            $config = [
                "assetic_integration" => true,
                "themes" => $themes,
                "active_theme" => $themes[0],
                'path_patterns' => [
                    'app_resource' => [
                        __DIR__.'/../Resources/themes/default/%%template%%'
                    ]
                ]
            ];

            $container->prependExtensionConfig("liip_theme", $config);

        }

    }
```

alter as needed, add it to your bundle extension.

**Comment by lsmith77** [comment]
@clytemnestra is correct .. you need to set a default.
