### ISSUE TITLE
Custom service as "liip_theme.autodetect_theme" setting

### ISSUE THREAD

**Issue by lshchur** [liip/LiipThemeBundle#170]
Hi there!

Conext:
symfony 3.2.13

I was attempting to put my custom service's id into that field.
My service was extended from Liip\ThemeBundle\Helper\DeviceDetection class, and in there I only overridden the  getType() method.

Basically that's it:

`<?php

namespace AppBundle\Utils;
use Liip\ThemeBundle\Helper\DeviceDetection as BaseDeviceDetection;

class DeviceDetection extends BaseDeviceDetection {

    public function getType(){

        $type = parent::getType();

        if($type == 'tablet'){
            $type = 'phone';
        }

        return $type;
    }

}`

However, this wasn't working properly. Somehow the class of the service was Liip\ThemeBundle\Helper\DeviceDetection. 

Why is that? Can you point me into right direction? I'd be happy to deliver a fix for this.
Thanks

**Comment by oleg-andreyev** [comment]
Did you override service definition?  So that it points to your new class

**Comment by lshchur** [comment]
Hi @oleg-andreyev , thanks for getting back to me so fast, much appreciated.

I end up with overriding that service, but I was under assumption that I don't have to override it, and can just point the id of my custom service into that setting, according to this piece of the documentation:

> Optionally autodetect_theme can also be set to a DIC service id that implements the Liip\ThemeBundle\Helper\DeviceDetectionInterface interface.

Did I get it wrong?

**Comment by oleg-andreyev** [comment]
@lshchur yes it should work, did you rebuild your cache after changing `autodetect_theme`?

**Comment by lshchur** [comment]
@oleg-andreyev , yes I did, and it didn't work. It wast still loading Liip\ThemeBundle\Helper\DeviceDetection instead of my class.

**Comment by 7thcubic** [comment]
https://github.com/liip/LiipThemeBundle/blob/72bbc1607ba98946e41ede016b74ae2dce2ee2fc/Resources/config/templating.xml#L45-L51

https://github.com/liip/LiipThemeBundle/blob/72bbc1607ba98946e41ede016b74ae2dce2ee2fc/DependencyInjection/LiipThemeExtension.php#L64-L68

Lets just say the extension did not set the auto detect theme for the service liip_theme.active_theme

a quick way to fix this is to just do

$container->setParameter('liip_theme.theme_auto_detect.class','your_class_here')

**Comment by lsmith77** [comment]
@lshchur can you try https://github.com/liip/LiipThemeBundle/pull/176 ?
