### ISSUE TITLE
User Deprecated: Passing "false" as the second argument to Symfony\Component\HttpKernel\Kernel::getBundle() is deprecated as of 3.4 and will be removed in 4.0.

### ISSUE THREAD

**Issue by krushnaghodke** [liip/LiipThemeBundle#179]
When i update symfony version from 3.3 to 3.4 showing deprecation.
[https://github.com/liip/LiipThemeBundle/blob/master/Locator/FileLocator.php#L185](url)

**Stack Trace:** 
`{▼
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:237 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Locator/FileLocator.php:185 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Locator/FileLocator.php:135 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Locator/TemplateLocator.php:85 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/liip/theme-bundle/Twig/Loader/FilesystemLoader.php:77 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:150 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/twig/twig/lib/Twig/Environment.php:330 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/twig/twig/lib/Twig/Environment.php:424 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:125 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:49 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:45 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php:72 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/sensio/framework-extra-bundle/EventListener/TemplateListener.php:107 {▶}
  Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener->onKernelView() {}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:104 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:139 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:158 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202 {▶}
  /Users/INV15092015/Work/projects/invcoachrack/web/app_dev.php:37 {▼
    › 
    › $response = $kernel->handle($request);
    › $response->setSharedMaxAge(604800);
    arguments: {▶}
  }
}`

**Comment by lsmith77** [comment]
we are aware of this API change and actually made a fix for it already. however due to BC we are still calling the API with the second parameter set to `false`. so essentially this deprecation cannot be fixed without a new major version, which I don’t intend to release just to fix this notice. I hope you understand
